stages:
 - dryrun
 - build

.defaults: &defaults
  tags:
   - grid5000-shell
  artifacts:
     paths:
      - apt-history.log
     expire_in: '1 week'

.defaults-dryrun: &defaults-dryrun
  stage: dryrun
  tags:
   - grid5000-docker
  script:
   - apt-get update && apt-get -y install ruby ruby-dev ruby-ffi && gem install kameleon-builder
   - kameleon info --dryrun $(echo $CI_JOB_NAME | cut -d _ -f 2).yaml

.defaults-build: &defaults-build
  stage: build
  tags:
   - grid5000-shell
  script:
   - /srv/ci-runner-scripts/bin/test-environment-newrecipes $(echo $CI_JOB_NAME | cut -d _ -f 2)
#  artifacts:
#   paths:
#    - build/*dsc
#    - build/*tar.gz
#   expire_in: '1 week'


dryrun_centos7-x64-min:
  <<: *defaults-dryrun

dryrun_ubuntu1804-x64-min:
  <<: *defaults-dryrun

dryrun_debiantesting-x64-min:
  <<: *defaults-dryrun

dryrun_debian9-x64-min:
  <<: *defaults-dryrun

dryrun_debian9-x64-base:
  <<: *defaults-dryrun

dryrun_debian9-x64-nfs:
  <<: *defaults-dryrun

dryrun_debian9-x64-xe,:
  <<: *defaults-dryrun

dryrun_debian9-x64-big:
  <<: *defaults-dryrun

dryrun_debian9-x64-std:
  <<: *defaults-dryrun


build_centos7-x64-min:
  <<: *defaults-build

build_ubuntu1804-x64-min:
  <<: *defaults-build

build_debiantesting-x64-min:
  <<: *defaults-build

build_debian9-x64-std:
  <<: *defaults-build