# Software Install
- enable_contrib: true
- enable_nonfree: true

- configure_source_list:
  - write_in:
    - /etc/apt/sources.list
    - |
      deb $${apt_repository} $${release} main
      deb-src $${apt_repository} $${release} main
      
      deb $${apt_repository} $${release}-backports main
      deb-src $${apt_repository} $${release}-backports main
      
      deb http://security.debian.org/ $${release}/updates main
      deb-src http://security.debian.org/ $${release}/updates main
      
      deb $${apt_repository} $${release}-updates main
      deb-src $${apt_repository} $${release}-updates main

- workaround-jessie-update-repo:
  - exec_in: |
      if [ $${release} = "jessie" ]; then
        sed -i '/jessie-updates/d' /etc/apt/sources.list;
        sed -i '/jessie-backports/d' /etc/apt/sources.list;
        echo "deb http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list;
        echo "deb http://archive.debian.org/debian jessie-backports-sloppy main" > /etc/apt/sources.list.d/backports-sloppy.list;
        echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/no_valid_check;
      fi

- add_contribs_and_nonfree_sources:
  - exec_in: |
      if [ $${enable_contrib} = true ]; then
        REPO_CONTRIB="contrib"
      fi
  - exec_in: |
      if [ $${enable_nonfree} = true ]; then
        REPO_NONFREE="non-free"
      fi
  - exec_in: perl -pi -e "s/main$/main $REPO_CONTRIB $REPO_NONFREE/" /etc/apt/sources.list
  - exec_in: |
      if [ $${release} = "jessie" ]; then
        perl -pi -e "s/main$/main $REPO_CONTRIB $REPO_NONFREE/" /etc/apt/sources.list.d/backports.list;
        perl -pi -e "s/main$/main $REPO_CONTRIB $REPO_NONFREE/" /etc/apt/sources.list.d/backports-sloppy.list;
      fi

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: apt-get -o Acquire::Check-Valid-Until=false -y --force-yes update
  - on_setup_clean:
    - exec_in: apt-get -y --force-yes autoclean
    - exec_in: apt-get -y --force-yes clean
    - exec_in: apt-get -y --force-yes autoremove
