# Software Install
- enable_contrib: true
- enable_nonfree: true
- enable_backports: true

- configure_source_list:
  - write_in:
    - /etc/apt/sources.list
    - |
      deb $${deb_mirror_uri} $${release} main
      deb-src $${deb_mirror_uri} $${release} main
      
      deb $${deb_mirror_uri}  $${release}-updates main
      deb-src $${deb_mirror_uri} $${release}-updates main
  - exec_in: |
      if [ "$${release}" != "sid" ]; then
        echo "deb http://security.debian.org/ $${release}/updates main" >> /etc/apt/sources.list
        echo "deb-src http://security.debian.org/ $${release}/updates main" >> /etc/apt/sources.list
      fi

- add_backports:
  - exec_in: |
      if [ "$${enable_backports}" == "true" -a "$${release}" != "testing" -a "$$release" != "sid" ]; then
        echo "deb $${deb_mirror_uri} $${release}-backports main" >> /etc/apt/sources.list
        echo "deb-src $${deb_mirror_uri} $${release}-backports main" >> /etc/apt/sources.list
      fi

- add_contribs_and_nonfree_sources:
  - exec_in: |
      if [ "$${enable_contrib}" == "true" ]; then
        REPO_CONTRIB=" contrib"
      fi
  - exec_in: |
      if [ "$${enable_nonfree}" == "true" ]; then
        REPO_NONFREE=" non-free"
      fi
  - exec_in: perl -pi -e "s/main$/main$REPO_CONTRIB$REPO_NONFREE/" /etc/apt/sources.list

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: apt-get -o Acquire::Check-Valid-Until=false -y --force-yes update
