- configure_sshd:
  - append_in:
    - /etc/ssh/sshd_config
    - |
      HostKey /etc/ssh/ssh_host_rsa_key
      PermitRootLogin without-password
      PermitUserEnvironment yes
- restart_sshd:
  - exec_in: systemctl restart sshd
