# System configuration

- set_timezone:
  - exec_in: ln -sf /usr/share/zoneinfo/$${timezone} /etc/localtime

- configure_GRUB:
  - exec_in: sed -i 's|^\(GRUB_CMDLINE_LINUX=\).*|\1"console=tty0 console=ttyS0,115200"|' /etc/default/grub
  - exec_in: update-grub

