# Software Install

- configure_source_list:
  - exec_in: echo "Not changing Ubuntu apt sources"

- update_repositories:
  # Deactivate the check to make the cache system works after a while...
  - exec_in: apt-get -o Acquire::Check-Valid-Until=false -y --force-yes update
