# System configuration
- GRUB_CMDLINE_LINUX: ""

- set_timezone:
  - exec_in: ln -sf /usr/share/zoneinfo/$${timezone} /etc/localtime

- configure_GRUB:
  - exec_in: sed -i 's|^\(GRUB_CMDLINE_LINUX=\).*|\1"$${GRUB_CMDLINE_LINUX}"|' /etc/default/grub
  - exec_in: update-grub

# Prevent systemd-networkd from enumarating devices before renaming by udev : https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=11050
- force_udev_before_systemd_networkd:
  - exec_in: mkdir -p /lib/systemd/system/systemd-networkd.service.d/
  - write_in:
    - /lib/systemd/system/systemd-networkd.service.d/after-udev.conf
    - |
      [Service]
      ExecStartPre=/sbin/udevadm settle
      EOF
